### ISSUE TITLE
功能很强大，但是为什么启动是会出现无法验证发布者的问题？

### ISSUE THREAD

**Issue by Landius** [runningcheese/RunningCheese-Firefox#18]
![image](https://user-images.githubusercontent.com/11910028/52518267-03f16380-2c83-11e9-8189-7354240f253f.png)

**Comment by runningcheese** [comment]
@Landius 我猜你用的是Win10 家庭版？

**Comment by Landius** [comment]
@runningcheese 啊，是的😯
