### ISSUE TITLE
v10[4.19 & 4.21]证书导入问题

### ISSUE THREAD

**Issue by northpark** [runningcheese/RunningCheese-Firefox#2]
自制的证书[goproxy.crt]可以导入v10第一版，但是v10[4.19 & 4.21]点击“导入证书”，选择同一个证书却无反应

**Comment by runningcheese** [comment]
可以导入的，你从字母G开始找，就会找到GoAgnet，如果Proxy拓展显示没有安装证书，那就是这个拓展的问题了。
