### ISSUE TITLE
关于mojave下页面右键菜单文字错位

### ISSUE THREAD

**Issue by valasco** [runningcheese/RunningCheese-Firefox#20]
如题 ，页面邮件菜单有查看页面信息、代码、元素三个选项，此菜单文字（“查看”二字）出现了错位与菜单前面的图标重叠。请教，在哪里修改菜单文字的位置，好修改偏移？

**Comment by runningcheese** [comment]
@valasco 有没有截图？ 在Windows下是没有问题的。
