### ISSUE TITLE
大部分附加组件忽然被强行停用

### ISSUE THREAD

**Issue by Jpvfsnrt** [runningcheese/RunningCheese-Firefox#21]
昨天，打开火狐，忽然跳出提示说是组件被强行停用，打开附加组件选项，显示：这些扩展不符合现今的 Firefox标准，因此已被停用。如下图：
![11111](https://user-images.githubusercontent.com/20756207/57175626-d3cff000-6e80-11e9-8af2-9dceb976ef4c.png)

**Comment by LeeXTZ** [comment]
这是火狐官方的锅，原版火狐最近的更新已经解决了，不知道这个跟进了没有

**Comment by runningcheese** [comment]
@Jpvfsnrt 参考：https://www.runningcheese.com/bulletin/6575
