### ISSUE TITLE
开始.bat不能使用

### ISSUE THREAD

**Issue by DoudouMee** [runningcheese/RunningCheese-Firefox#23]
![QQ截图20190608131324](https://user-images.githubusercontent.com/43898894/59142354-b3e79b00-89ef-11e9-9895-4ac111e80893.jpg)

**Comment by runningcheese** [comment]
使用管理员身份运行看看，这个 tmp.vbs 怎么来了，原文件里是 开始.bat 这个文件

**Comment by DoudouWe** [comment]
使用管理员身份运行也是一样的， tmp.vbs 是双击 开始.bat 后在相同目录下产生的，关掉上面的对话框会自动消失
