### ISSUE TITLE
页面的右键菜单有点乱，我想单独把这个菜单恢复成默认的，应该改哪里呢？

### ISSUE THREAD

**Issue by db-one** [runningcheese/RunningCheese-Firefox#3]
![snipaste20180516_171617](https://user-images.githubusercontent.com/20243226/40108345-3546f564-592d-11e8-88ae-78dcff75cf3e.jpg)

想恢复成这样的页面右键菜单怎么改
chrome\css\chrome.css我找到是这个文件定义的，但是没找到具体的参数，求帮助

**Comment by runningcheese** [comment]
css文件夹里去除 chrome.css 就可以了。

**Comment by kangmya** [comment]
@runningcheese 那样整个界面的定制UI都没了，我想保持现有的UI，仅仅还原页面右键的有办法吗

**Comment by kangmya** [comment]
@runningcheese 嗯 刚刚搞定了，主要是第四第五个大类里面的几个参数，删除了就好了

**Comment by chonghua** [comment]
大神，我想自己定制下firefox，比如说使用uesrchromejs功能，但是从官方下载uc管理器安装不上，请问应该如何操作呢，谢谢啦

**Comment by yj7778826** [comment]
> 
> 
> @runningcheese 嗯 刚刚搞定了，主要是第四第五个大类里面的几个参数，删除了就好了

怎么搞？求解答，主要是把右键的4大金刚键找回来，这个是关键

**Comment by kangmya** [comment]
@yj7778826 chrome\css\chrome.css这个文件里面 查找下面的配置   删除掉就可以了   他文件配置里面都有说明  自己根据自己需要删除  然后重启浏览器生效


/* 隐藏链接右键菜单 Hidn link menu option*/
#context-copylink,
#context-savelink,
#context-openlinkincurrent,
#context-savelinktopocket,
#context-openlinkinusercontext-menu,
#context-openlinkprivate,
#context-openlink,
#context-sep-open,
#context-bookmarklink,
#context-navigation,
#screenshots_mozilla_org_create-screenshot,
#context-viewbgimage,
#context-sep-viewsource,
#context-sep-navigation {
	display: none;
}


/*隐藏标签右键菜单 Hide tabs menu option*/
#context_reloadTab,
#context_undoCloseTab,
#context_closeTab,
#context_openTabInWindow,
#context_reloadAllTabs,
#context_closeOtherTabs,
#context_closeTabsToTheEnd,
#context_openTabInWindow + menuseparator,
#context_closeOtherTabs + menuseparator,
#context_sendTabToDevice + menuseparator,
#context_duplicateTab + menuseparator,
#context_toggleMuteTab + menuseparator
 {
	display: none;
}


/*标签页右键菜单排序 Tabs Option Order*/
#context_CopyTab {-moz-box-ordinal-group: 1 !important;}
#context_pinTab, #context_unpinTab {-moz-box-ordinal-group: 2 !important;}
#context_CloseTab {-moz-box-ordinal-group: 3 !important;}
#context_SidebarOpen {-moz-box-ordinal-group: 4 !important;}
#context_toggleMuteTab{-moz-box-ordinal-group: 5 !important;}
#context_SmallWindow {-moz-box-ordinal-group: 6 !important;}
#context_sendTabToDevice {-moz-box-ordinal-group: 7 !important;}
#context_bookmarkAllTabs {-moz-box-ordinal-group: 13 !important;}
#context_TabInfoCopy {-moz-box-ordinal-group: 15 !important;}  	


/*文字选中菜单排序 Text Selection Menu Order*/
#addmenu_context-copy{-moz-box-ordinal-group:0 !important;}
#context-searchselect{-moz-box-ordinal-group:1 !important;}
[id*="olivier_debroqueville_gmail_com_"]{-moz-box-ordinal-group:2 !important;}
#context-keywordfield{-moz-box-ordinal-group:3 !important;}
[id*="addsearch_burningmoth_com_"]{-moz-box-ordinal-group:3 !important;}
#context-viewpartialsource-selection{-moz-box-ordinal-group:5 !important;}
#context-inspect{-moz-box-ordinal-group:5 !important;}
#addmenu_context-translate{-moz-box-ordinal-group:5 !important;}





/*隐藏页面右键菜单 Hide Page menu option*/
#context-pocket,
#context-savepage,
#context-selectall,
#inspect-separator,
#context-sep-viewbgimage,
#fill-login,
#context-keywordfield,
#context-media-eme-learnmore + menuseparator,
#context-sep-selectall,
[id*="support_lastpass_com-menuitem-"],
[id*="_cd7e22de-2e34-40f0-aeff-cec824cbccac_-menuitem-"],
[id*="mozilla_cc3_internetdownloadmanager_com-menuitem-9"],
[id*="mozilla_cc3_internetdownloadmanager_com-menuitem-1"],
[id*="mozilla_cc3_internetdownloadmanager_com-menuitem-2"],
#thunder_cross-menuitem-_contextDownloadLink,
#context-sendaudio,
#context-sep-sendlinktodevice,
#context-searchselect{
	display: none !important;
}



/*隐藏图像右键菜单 Hide Image menu option*/
#context-sendimage,
#context-setDesktopBackground, 
#context-copyimage {
	display: none;
}


/*隐藏HTML5视频右键菜单 Hide video menu option*/
#context-media-pause,
#context-media-mute,
#context-media-unmute,
#context-media-hidecontrols,
#context-sendvideo,
#context-media-loop{
	display: none;
}


/*隐藏书签右键菜单 Hide Bookmark Menu Option*/
#placesContext_open,
#placesContext_ExportHTMLFolderSep,
[id="placesContext_open:newwindow"],
[id="placesContext_openContainer:tabs"],
[id="placesContext_open:newprivatewindow"]{
	display: none;
}




/*隐藏输入框右键 Hide Text area option*/
#spell-separator,
#spell-add-dictionaries-main,
#context-sep-paste,
#spell-dictionaries {
	display: none;
}

**Comment by jdfq** [comment]
我用的是Firefox原版84，现在选中文本后右键，菜单多出了“打印选中内容”和“截图”，我想删除，但不知道菜单对象id，求指教。
