### ISSUE TITLE
书签栏会经常隐藏

### ISSUE THREAD

**Issue by liy516** [runningcheese/RunningCheese-Firefox#31]
如题！每次都要重现勾选才能显示，比较麻烦

**Comment by ddddg929** [comment]
> 
> 
> 如题！每次都要重现勾选才能显示，比较麻烦

双击就好了

**Comment by liy516** [comment]
> > 如题！每次都要重现勾选才能显示，比较麻烦
> 
> 双击就好了
双击下确实就显示了，谢谢

**Comment by yqmy0814** [comment]
2、通过 UC 脚本可以新增了一些默认没有的书签打开方式，比如书签工具栏的打开逻辑：

• 双击「地址栏」显示或关闭书签栏
• 双击「空白处」关闭书签栏

修改方法是可以打开文件 ..\Profiles\V10\chrome\SubScript\ButtonEventListener.uc.js，搜索“双击地址栏”，将相关代码删除后保存，同时将 Firefox 根目录下的“Cache”文件夹删除，重启一下就可以了。

使用手册里有提到怎么设置
