### ISSUE TITLE
主题设置为“default”后，重启Firefox，鼠标手势必然失效

### ISSUE THREAD

**Issue by ghost** [runningcheese/RunningCheese-Firefox#35]
- System
window7  
RunningCheese Firefox（2020-05-11 76.0.1 正式版） 
- 问题
之前遇到过鼠标手势失效的情况，于是从压缩包重新解压一个新的firefox配置文件夹，在浏览器中禁用了几个扩展，新标签页的壁纸刷新几次，第三次重启Firefox的时候，鼠标手势莫名其妙不能用了

**Comment by the-one-step** [comment]
发现真正原因了：把Firefox主题设置为`默认`，重启Firefox后，鼠标手势100%失效，把主题重新设置为`明亮`后，重启Firefox，鼠标手势有正常可用了。
希望修复下，毕竟windows7用户还是更喜欢透明标题栏的
> 
![transparency](https://user-images.githubusercontent.com/52375886/86344763-4149fd00-bc8d-11ea-9cf1-682e4e32b6cc.jpg)
> 
![截屏图片](https://user-images.githubusercontent.com/52375886/86344765-427b2a00-bc8d-11ea-90e0-3e5cb95a1bec.jpg)
