### ISSUE TITLE
Firefox 106.0 正式版似乎去除了画中画控件功能

### ISSUE THREAD

**Issue by MagicCD** [runningcheese/RunningCheese-Firefox#39]
# Firefox 106.0 正式版去除了画中画控件

尊敬的作者您好！感谢您对项目软件的付出和贡献

环境：Windows 11 Professional
软件版本：RunningCheese Firefox 106.0 正式版

出现的问题：我之前使用的是您开发改进的 RunningCheese Firefox v89。由于近期使用过程中需要升级浏览器版本，故访问您的官方网站下载 Firefox 106.0 正式版，按照教程替换更新操作后，**发现设置中的开启画中画功能缺失**

以下是功能对比，请您查看
![这是之前的老版本的浏览界面](https://img.comcw.cn/uploadimg/image/20220815/20220815155424_54796.jpg)
![这是106.0版本的浏览界面](https://user-images.githubusercontent.com/87908620/201366831-86d4008f-38b6-447f-8bd6-73b482853ba6.png)

**Comment by MagicCD** [comment]
这个功能对于我来说有非同一般的地位和重要性，再次感谢奶酪大大开发者的付出

**Comment by Tinhone** [comment]
https://support.mozilla.org/zh-CN/kb/Firefox 的画中画功能
